### ISSUE TITLE
v0.3.13 TypeError: Cannot assign to read only property

### ISSUE THREAD

**Issue by chrisblossom** [gcanti/babel-plugin-tcomb#124]
After updating to from ``0.3.12`` to ``0.3.13`` I am getting the following error:

```js
  error: [TypeError: Cannot assign to read only property '/path/1/' of [object Object]] }
    at Logger.error (webpack:///./src/helpers/logger.js:102:15)
    at process.<anonymous> (webpack:///./src/server.js:69:16)
    at emitTwo (events.js:92:20)
    at process.emit (events.js:172:7)
    at process.emit (/Users/chris/github/app/node_modules/source-map-support/source-map-support.js:419:21)
    at /Users/chris/github/app/node_modules/core-js/modules/es6.promise.js:113:19
    at perform (/Users/chris/github/app/node_modules/core-js/modules/es6.promise.js:59:5)
    at Immediate._onImmediate (/Users/chris/github/app/node_modules/core-js/modules/es6.promise.js:111:16)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Is this expected in the new release? (pointing out an error in my code)

**Comment by gcanti** [comment]
v0.3.13 enfoces immutability, maybe you are tryng to modify a frozen object? The debugger should help in these cases

**Comment by chrisblossom** [comment]
This was the issue I was running into. Thank you
