### ISSUE TITLE
Type declarations do not work with destructuring parameters

### ISSUE THREAD

**Issue by gajus** [gcanti/babel-plugin-tcomb#144]
```js
type TestType = {topics: Array<Object>};

GuideListComponent = ({topics}: TestType) => {
// ...
```

This gives an error:

```
TypeError: [tcomb] Invalid value undefined supplied to { topics }: TestType/topics: Array<Object> (expected an array of Object)
    at Function.fail (/node_modules/tcomb/lib/fail.js:2:9)
    at assert (/node_modules/tcomb/lib/assert.js:14:12)
    at List (/node_modules/tcomb/lib/list.js:35:7)
    at create (/node_modules/tcomb/lib/create.js:9:104)
    at Interface (/node_modules/tcomb/lib/interface.js:70:22)
    at _assert (isomorphic-webpack:240:7)
    at GuideListComponent (/src/client/components/GuideListComponent/index.js:57:45)
    at WrappedComponent (/node_modules/react-css-modules/dist/wrapStatelessFunction.js:55:38)
    at /node_modules/react-dom/lib/ReactCompositeComponent.js:306:16
    at measureLifeCyclePerf (/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
```

when executed with `[{}]`.

In the mean time, this works:

```js
type TestType = {topics: Array<Object>};

GuideListComponent = (props: TestType) => {
// ...
```

**Comment by gcanti** [comment]
Thanks for reporting. This is a regression introduced while solving https://github.com/gcanti/babel-plugin-tcomb/issues/141. The issue is that I can't use `arguments` with arrow functions. I got a (partial) fix on the 144 branch if you want to try it out (`lib` is commited in so you can install the plugin from github: `npm i gcanti/babel-plugin-tcomb#144`)
