### ISSUE TITLE
Support complicated object property name

### ISSUE THREAD

**Issue by MrEfrem** [gcanti/babel-plugin-tcomb#89]
Type definition:
```
type MyType = {
      'cc:id': number,
      '@members': ?Array<string>,
};
```

Stack trace:
```
node_modules/babel-core/lib/transformation/file/index.js:591
      throw err;
      ^

TypeError: server/middleware/api/dictionaries.js: Cannot read property '0' of null

    at Generator._maybeIndent (node_modules/babel-generator/lib/printer.js:263:51)
    at Generator._append (node_modules/babel-generator/lib/printer.js:253:10)
    at Generator.word (node_modules/babel-generator/lib/printer.js:157:10)
    at Generator.Identifier (node_modules/babel-generator/lib/generators/types.js:43:8)
    at node_modules/babel-generator/lib/printer.js:372:23
    at Buffer.withSource (node_modules/babel-generator/lib/buffer.js:180:5)
    at Generator.withSource (node_modules/babel-generator/lib/printer.js:238:15)
    at Generator.print (node_modules/babel-generator/lib/printer.js:371:10)
    at Generator.ObjectProperty (node_modules/babel-generator/lib/generators/types.js:90:10)
    at node_modules/babel-generator/lib/printer.js:372:23
```

**Comment by gcanti** [comment]
Thanks @MrEfrem, I'll publish a fix asap

**Comment by gcanti** [comment]
Released a fix in https://github.com/gcanti/babel-plugin-tcomb/releases/tag/v0.3.10

**Comment by MrEfrem** [comment]
Thx @gcanti.
