### ISSUE TITLE
Module parse failed on async function error

### ISSUE THREAD

**Issue by chrisblossom** [gcanti/babel-plugin-tcomb#95]
I am unable to get async functions to work when a return value is specified. Is this a bug or am I doing something wrong?

```js
const somePromise = (): any => new Promise((resolve: any): any => resolve);

const asyncFunction = async(): Promise<string> => {
  await somePromise();

  return 'done';
};
```
 
```js
ERROR in ./src/server.js
Module parse failed: /Users/chris/github/app/node_modules/babel-loader/index.js?{"passPerPreset":true,"presets":["stage-2","react","es2015"],"plugins":["transform-jscript","transform-es3-member-expression-literals","transform-es3-property-literals"],"env":{"development":{"plugins":["tcomb"]},"production":{"plugins":["transform-react-remove-prop-types","transform-react-constant-elements","transform-react-inline-elements"]},"test":{"plugins":["rewire"]}}}!/Users/chris/github/app/src/server.js The keyword 'yield' is reserved (541:18)
You may need an appropriate loader to handle this file type.
SyntaxError: The keyword 'yield' is reserved (541:18)
    at Parser.pp$4.raise (/Users/chris/github/app/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$3.parseIdent (/Users/chris/github/app/node_modules/acorn/dist/acorn.js:2182:14)
    at Parser.pp$3.parseExprAtom (/Users/chris/github/app/node_modules/acorn/dist/acorn.js:1774:21)
    at Parser.pp$3.parseExprSubscripts (/Users/chris/github/app/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/chris/github/app/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/chris/github/app/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/chris/github/app/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/chris/github/app/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/chris/github/app/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/Users/chris/github/app/node_modules/acorn/dist/acorn.js:727:47)
 @ multi main
```

```js
{
  "passPerPreset": true,
  "presets": [
    "stage-2",
    "react",
    "es2015"
  ],
  "plugins": [
    "transform-jscript",
    "transform-es3-member-expression-literals",
    "transform-es3-property-literals"
  ],
  "env": {
    "development": {
      "plugins": [
        "tcomb"
      ]
    },
    "production": {
      "plugins": [
        "transform-react-remove-prop-types",
        "transform-react-constant-elements",
        "transform-react-inline-elements"
      ]
    },
    "test": {
      "plugins": [
        "rewire"
      ]
    }
  }
}
```
I have the same result when manually calling in 

```js
  "plugins" : [
    "syntax-flow",
    "tcomb",
    "transform-flow-strip-types"
  ]
```

**Comment by gcanti** [comment]
@chrisblossom async / await is not officially supported. I published a patch though (https://github.com/gcanti/babel-plugin-tcomb/releases/tag/v0.3.11). Your build should not break anymore

**Comment by chrisblossom** [comment]
Thanks for getting this done so quickly! This fixed my issue for all but one of my declarations. I tried to reproduce with a test but haven't been able to yet. I will get you more information as soon as I figure out what circumstances are causing it to break.

It happens to be a nested await function so thought that might be causing it. Here is the test I was trying: 
```js
const cb = cb => cb;
const somePromise = (): Promise<void> => new Promise((resolve: Function): void =>
    cb((): void => {

      return resolve();
    }));

async function foo1(): Promise<string> {
  return cb('test', async (): Promise<void> => {
    await somePromise();

    return await bar();
  });
}
```
